# LUMINAFLEX OS | DOCKERFILE PRODUCTION
# NODO: AURUM_CORE_V2
# PROTOCOLO: 741 8 520

# STAGE 1: Build Engine
FROM node:20-alpine AS builder

WORKDIR /app

# Instalación de dependencias
COPY package*.json ./
RUN npm install

# Copia de código fuente
COPY . .

# Inyección de variables en tiempo de construcción (Vite)
ARG API_KEY
ARG DATABASE_URL
ENV VITE_API_KEY=$API_KEY
ENV VITE_DATABASE_URL=$DATABASE_URL

# Build industrial
RUN npm run build

# STAGE 2: High Availability Server (Nginx)
FROM nginx:stable-alpine

# Copia de los archivos estáticos desde el builder
COPY --from=builder /app/dist /usr/share/nginx/html

# Inyección de la configuración de Aurum Shield
COPY nginx.conf.txt /etc/nginx/conf.d/default.conf

# Healthcheck para monitoreo del Nodo
HEALTHCHECK --interval=30s --timeout=3s \
  CMD curl -f http://localhost:3000/ || exit 1

EXPOSE 3000
CMD ["nginx", "-g", "daemon off;"]
